"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "fr" | "en"

type LanguageContextType = {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const translations = {
  fr: {
    // Header
    home: "Accueil",
    food: "Alimentation",
    products: "Produits",
    services: "Services",
    about: "À Propos",
    contact: "Contact",
    
    // Buttons & Common
    learnMore: "En savoir plus",
    requestQuote: "Demander un devis",
    contactUs: "Nous contacter",
    addToCart: "Ajouter au panier",
    promo: "Promo",
    callNow: "Appeler maintenant",
    other: "Autre",

    // Categories
    category: "Catégorie",
    price: "Prix",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    search: "Rechercher",
    all: "Tous",
    riz: "Riz",
    huiles: "Huiles",
    conserves: "Conserves",
    légumineuses: "Légumineuses",
    céréales: "Céréales",
    condiments: "Condiments",
    dentifrice: "Dentifrice",
    savons: "Savons",
    shampoings: "Shampoings",
    crèmes: "Crèmes",
    parfums: "Parfums",
    soinsCorps: "Soins du corps",
    piscines: "Piscines",
    batiments: "Bâtiments",
    routes: "Routes",

    // Home page
    heroSubtitle:
      "Votre partenaire de confiance pour l'alimentation, les produits cosmétiques et les services de construction",
    discoverServices: "Découvrir nos services",
    ourActivities: "Nos Activités",
    ourActivitiesSubtitle: "Trois pôles d'expertise pour répondre à tous vos besoins",
    foodTitle: "Alimentation",
    foodDesc: "Riz et denrées de base",
    foodCardDesc: "Large gamme de produits alimentaires de qualité : riz, huiles, conserves et autres denrées essentielles pour votre quotidien.",
    viewCatalog: "Voir le catalogue",
    productsTitle: "Produits Cosmétiques",
    productsDesc: "Cosmétiques et hygiène",
    productsCardDesc: "Découvrez notre sélection de produits cosmétiques : pâtes dentifrice, savons, shampoings et soins pour toute la famille.",
    discoverProducts: "Découvrir les produits",
    servicesTitle: "Services de Construction",
    servicesDesc: "Construction et génie civil",
    servicesCardDesc: "Construction et entretien de piscines, routes et bâtiments. Expertise complète en génie civil pour vos projets.",
    ourServices: "Nos services",
    featuredCosmetics: "Nos Produits Cosmétiques",
    featuredCosmeticsDesc: "Une sélection de nos meilleurs produits cosmétiques.",
    viewAllProducts: "Voir tous les produits",
    ourServicesDesc: "Des solutions professionnelles pour la construction et le génie civil.",
    viewAllServices: "Voir tous les services",
    featuredFoodProducts: "Nos Produits Alimentaires",
    featuredFoodProductsDesc: "Découvrez notre sélection de denrées alimentaires de première qualité.",
    viewAllFoodProducts: "Voir tous les produits alimentaires",
    aboutTitle: "À Propos",
    aboutSectionDesc: "ETS ROYAL COMPANY SERVICE est une entreprise polyvalente qui opère dans trois domaines complémentaires. Nous nous engageons à fournir des produits et services de qualité supérieure à nos clients.",
    yearsExperience: "Années d'expérience",
    satisfiedClients: "Clients satisfaits",
    activityPoles: "Pôles d'activité",
    readyToStart: "Prêt à démarrer votre projet ?",
    readyToStartDesc: "Contactez-nous dès aujourd'hui pour discuter de vos besoins et obtenir un devis personnalisé",

    // Services Page
    servicesPageSubtitle: "Expertise complète en construction de piscines, bâtiments, génie civil et entretien",
    completedProjects: "Projets réalisés",
    projectWarranty: "Garantie projets",
    servicesGridSubtitle: "Une gamme complète de services pour tous vos projets de construction",
    ourProjects: "Nos Réalisations",
    ourProjectsDesc: "Découvrez quelques-uns de nos projets récemment réalisés",
    ourProcess: "Notre Processus",
    ourProcessDesc: "Un processus éprouvé pour garantir la réussite de votre projet",
    servicesCtaDesc: "Contactez-nous pour une consultation gratuite et un devis détaillé",
    requestFreeQuote: "Demander un devis gratuit",
    servicePiscineTitle: "Construction de Piscines",
    servicePiscineDesc: "Conception et construction de piscines résidentielles et commerciales sur mesure.",
    servicePiscineFeature1: "Piscines enterrées et semi-enterrées",
    servicePiscineFeature2: "Systèmes de filtration moderne",
    servicePiscineFeature3: "Aménagement paysager",
    servicePiscineFeature4: "Éclairage LED intégré",
    serviceBatimentTitle: "Construction de Bâtiments",
    serviceBatimentDesc: "Construction complète de bâtiments résidentiels, commerciaux et industriels.",
    serviceBatimentFeature1: "Maisons individuelles",
    serviceBatimentFeature2: "Immeubles commerciaux",
    serviceBatimentFeature3: "Rénovation et extension",
    serviceBatimentFeature4: "Entrepôts industriels",
    serviceRouteTitle: "Génie Civil & Routes",
    serviceRouteDesc: "Travaux de génie civil et construction de voiries pour les secteurs public et privé.",
    serviceRouteFeature1: "Construction de routes",
    serviceRouteFeature2: "Terrassement",
    serviceRouteFeature3: "Drainage et assainissement",
    serviceRouteFeature4: "Fondations spéciales",
    serviceEntretienTitle: "Entretien & Maintenance",
    serviceEntretienDesc: "Services d'entretien et de maintenance pour toutes vos infrastructures",
    serviceEntretienFeature1: "Maintenance de piscines",
    serviceEntretienFeature2: "Réparations bâtiments",
    serviceEntretienFeature3: "Entretien voirie",
    serviceEntretienFeature4: "Contrats de maintenance",
    galleryPiscineLuxe: "Piscine Résidentielle Luxe",
    galleryImmeubleCommercial: "Immeuble Commercial",
    galleryRouteUrbaine: "Route Urbaine",
    galleryPiscineOlympique: "Piscine Olympique",
    galleryVillaModerne: "Villa Moderne",
    galleryInfraRoutiere: "Infrastructure Routière",
    processConsultation: "Consultation",
    processConsultationDesc: "Analyse de vos besoins et étude de faisabilité",
    processDevis: "Devis",
    processDevisDesc: "Proposition détaillée avec estimation des coûts",
    processRealisation: "Réalisation",
    processRealisationDesc: "Exécution du projet par nos équipes expertes",
    processLivraison: "Livraison",
    processLivraisonDesc: "Réception des travaux et garantie assurée",

    // Alimentation Page
    foodPageSubtitle: "Découvrez notre large gamme de produits alimentaires de qualité : riz, huiles, conserves et denrées essentielles",
    searchProduct: "Rechercher un produit...",
    noProductFound: "Aucun produit trouvé",
    qualityGuaranteed: "Produits de Qualité Garantie",
    qualityGuaranteedDesc: "Tous nos produits alimentaires sont soigneusement sélectionnés pour leur qualité et leur fraîcheur. Nous travaillons avec des fournisseurs de confiance pour vous garantir les meilleurs prix.",
    contactForBulk: "Contactez-nous pour vos commandes en gros",
    "Riz Parfumé Thai": "Riz Parfumé Thai",
    "Riz Blanc Local": "Riz Blanc Local",
    "Riz Basmati": "Riz Basmati",
    "Huile de Palme": "Huile de Palme",
    "Huile d'Arachide": "Huile d'Arachide",
    "Huile Végétale": "Huile Végétale",
    "Tomates Concentrées": "Tomates Concentrées",
    "Sardines à la Tomate": "Sardines à la Tomate",
    "Maïs en Grains": "Maïs en Grains",
    "Haricots Blancs": "Haricots Blancs",
    "Lentilles": "Lentilles",
    "Pois Chiches": "Pois Chiches",
    "Farine de Blé": "Farine de Blé",
    "Semoule de Maïs": "Semoule de Maïs",
    "Sel de Cuisine": "Sel de Cuisine",

    // Produits Page
    productsPageSubtitle: "Une gamme complète de produits cosmétiques et d'hygiène pour toute la famille",
    searchProductOrBrand: "Rechercher un produit ou une marque...",
    currentPromotions: "Promotions du moment",
    currentPromotionsDesc: "Profitez de nos offres spéciales sur une sélection de produits",
    ourPartnerBrands: "Nos Marques Partenaires",
    bulkOrder: "Commande en Gros",
    bulkOrderDesc: "Vous êtes un revendeur ? Profitez de nos tarifs préférentiels pour les achats en volume",
    requestProQuote: "Demander un devis professionnel",
    "Dentifrice Blancheur": "Dentifrice Blancheur",
    "Dentifrice Protection Complète": "Dentifrice Protection Complète",
    "Dentifrice Herbes Naturelles": "Dentifrice Herbes Naturelles",
    "Savon Noir Africain": "Savon Noir Africain",
    "Savon au Karité": "Savon au Karité",
    "Savon Antibactérien": "Savon Antibactérien",
    "Savon Doux pour Bébé": "Savon Doux pour Bébé",
    "Shampoing Cheveux Secs": "Shampoing Cheveux Secs",
    "Shampoing Anti-Pelliculaire": "Shampoing Anti-Pelliculaire",
    "Shampoing Pour Enfants": "Shampoing Pour Enfants",
    "Crème Hydratante Visage": "Crème Hydratante Visage",
    "Crème Anti-Age": "Crème Anti-Age",
    "Crème Éclaircissante": "Crème Éclaircissante",
    "Parfum Homme Sport": "Parfum Homme Sport",
    "Parfum Femme Floral": "Parfum Femme Floral",
    "Lait Corporel Nourrissant": "Lait Corporel Nourrissant",
    "Fresh Smile": "Fresh Smile",
    "DentalCare": "DentalCare",
    "NaturaFresh": "NaturaFresh",
    "African Beauty": "African Beauty",
    "Shea Nature": "Shea Nature",
    "ProtectPlus": "ProtectPlus",
    "BabyCare": "BabyCare",
    "HydraHair": "HydraHair",
    "ScalpCare": "ScalpCare",
    "KidsClean": "KidsClean",
    "GlowSkin": "GlowSkin",
    "YouthRevive": "YouthRevive",
    "BrightGlow": "BrightGlow",
    "Elite Men": "Elite Men",
    "Elegance": "Elegance",
    "BodyCare": "BodyCare",

    // About Page
    aboutPageTitle: "À Propos de ETS ROYAL COMPANY SERVICE",
    ourStoryTitle: "Notre Histoire",
    ourStoryDesc1: "Fondée il y a plus de 10 ans, ETS ROYAL COMPANY SERVICE a commencé comme une petite entreprise familiale avec une grande vision : fournir des produits et services essentiels de qualité à notre communauté.",
    ourStoryDesc2: "Au fil des années, nous avons élargi nos activités pour inclure trois pôles majeurs : l'alimentation générale, les produits cosmétiques et les services de construction. Cette diversification nous permet de répondre à une plus large gamme de besoins tout en maintenant notre engagement envers l'excellence.",
    ourStoryDesc3: "Aujourd'hui, nous sommes fiers d'être un acteur majeur dans nos domaines d'activité, reconnus pour notre fiabilité, notre intégrité et la qualité de notre travail.",
    ourCompanyAlt: "Notre entreprise",
    ourValuesTitle: "Nos Valeurs",
    ourValuesDesc: "Les principes qui guident chacune de nos actions.",
    valueQualityTitle: "Qualité",
    valueQualityDesc: "Nous nous engageons à fournir des produits et services qui respectent les plus hauts standards de qualité.",
    valueIntegrityTitle: "Intégrité",
    valueIntegrityDesc: "Nous opérons avec transparence et honnêteté dans toutes nos interactions.",
    valueSatisfactionTitle: "Satisfaction Client",
    valueSatisfactionDesc: "La satisfaction de nos clients est au cœur de nos priorités. Nous écoutons et répondons à leurs besoins.",
    valueInnovationTitle: "Innovation",
    valueInnovationDesc: "Nous cherchons constamment à innover pour améliorer nos offres et nos processus.",
    ourTeamTitle: "Notre Équipe",
    ourTeamDesc: "Rencontrez les leaders qui pilotent notre entreprise vers le succès.",
    teamRoleCEO: "Fondateur & CEO",
    teamRoleCOO: "Directrice des Opérations",
    teamRoleConstructionManager: "Chef de Projet Construction",
    teamRoleFoodManager: "Responsable Alimentation",
    workTogetherTitle: "Travaillons Ensemble",
    workTogetherDesc: "Contactez-nous dès aujourd'hui pour discuter de vos besoins et découvrir comment nous pouvons vous aider.",

    // Contact Page
    contactPageSubtitle: "Une question ? Un projet ? Notre équipe est à votre écoute pour vous accompagner",
    phone: "Téléphone",
    email: "Email",
    address: "Adresse",
    formTitle: "Envoyez-nous un message",
    formDescription: "Remplissez le formulaire ci-dessous et nous vous répondrons rapidement",
    formFullName: "Nom complet",
    formFullNamePlaceholder: "Votre nom",
    formEmail: "Email",
    formEmailPlaceholder: "votre@email.com",
    formPhone: "Téléphone",
    formCategory: "Catégorie",
    formSelectCategory: "Sélectionnez une catégorie",
    formSubject: "Sujet",
    formSubjectPlaceholder: "Objet de votre message",
    formMessage: "Message",
    formMessagePlaceholder: "Décrivez votre demande en détail...",
    formSubmitting: "Envoi en cours...",
    formSubmit: "Envoyer le message",
    toastSuccessTitle: "Message envoyé !",
    toastSuccessDescription: "Nous vous répondrons dans les plus brefs délais.",
    openingHours: "Horaires d'ouverture",
    mondayFriday: "Lundi - Vendredi",
    saturday: "Samedi",
    sunday: "Dimanche",
    closed: "Fermé",
    needQuoteTitle: "Besoin d'un devis ?",
    needQuoteDesc: "Obtenez une estimation gratuite et détaillée pour votre projet en moins de 48h",
    needQuoteFeature1: "Devis gratuit et sans engagement",
    needQuoteFeature2: "Réponse rapide sous 48h",
    needQuoteFeature3: "Conseils personnalisés",
    faqTitle: "FAQ Rapide",
    faq1Title: "Livraison disponible ?",
    faq1Desc: "Oui, pour toutes les commandes en gros",
    faq2Title: "Paiement accepté ?",
    faq2Desc: "Espèces, Mobile Money, Virement",
    faq3Title: "Garantie travaux ?",
    faq3Desc: "Garantie de 5 ans sur tous nos projets",
    ourOffices: "Nos Bureaux",
    mapPlaceholder: "Carte interactive bientôt disponible",

    // Footer
    quickLinks: "Liens rapides",
    country: "Cameroun",
    allRightsReserved: "Tous droits réservés.",
  },
  en: {
    // Header
    home: "Home",
    food: "Food",
    products: "Products",
    services: "Services",
    about: "About",
    contact: "Contact",

    // Buttons & Common
    learnMore: "Learn more",
    requestQuote: "Request a quote",
    contactUs: "Contact Us",
    addToCart: "Add to cart",
    promo: "Sale",
    callNow: "Call now",
    other: "Other",

    // Categories
    category: "Category",
    price: "Price",
    inStock: "In stock",
    outOfStock: "Out of stock",
    search: "Search",
    all: "All",
    riz: "Rice",
    huiles: "Oils",
    conserves: "Canned Goods",
    légumineuses: "Legumes",
    céréales: "Cereals",
    condiments: "Condiments",
    dentifrice: "Toothpaste",
    savons: "Soaps",
    shampoings: "Shampoos",
    crèmes: "Creams",
    parfums: "Perfumes",
    soinsCorps: "Body Care",
    piscines: "Pools",
    batiments: "Buildings",
    routes: "Roads",

    // Home page
    heroSubtitle: "Your trusted partner for food, cosmetic products and construction services",
    discoverServices: "Discover our services",
    ourActivities: "Our Activities",
    ourActivitiesSubtitle: "Three areas of expertise to meet all your needs",
    foodTitle: "Food Supply",
    foodDesc: "Rice and basic foodstuffs",
    foodCardDesc: "Wide range of quality food products: rice, oils, canned goods and other essential foodstuffs for your daily life.",
    viewCatalog: "View catalog",
    productsTitle: "Cosmetic Products",
    productsDesc: "Cosmetics and hygiene",
    productsCardDesc: "Discover our selection of cosmetic products: toothpaste, soaps, shampoos and treatments for the whole family.",
    discoverProducts: "Discover the products",
    servicesTitle: "Construction Services",
    servicesDesc: "Construction and civil engineering",
    servicesCardDesc: "Construction and maintenance of swimming pools, roads and buildings. Complete expertise in civil engineering for your projects.",
    ourServices: "Our services",
    featuredCosmetics: "Our Cosmetic Products",
    featuredCosmeticsDesc: "A selection of our best cosmetic products.",
    viewAllProducts: "View all products",
    ourServicesDesc: "Professional solutions for construction and civil engineering.",
    viewAllServices: "View all services",
    featuredFoodProducts: "Our Food Products",
    featuredFoodProductsDesc: "Discover our selection of premium quality foodstuffs.",
    viewAllFoodProducts: "View all food products",
    aboutTitle: "About Us",
    aboutSectionDesc: "ETS ROYAL COMPANY SERVICE is a versatile company that operates in three complementary fields. We are committed to providing superior quality products and services to our customers.",
    yearsExperience: "Years of experience",
    satisfiedClients: "Satisfied clients",
    activityPoles: "Activity poles",
    readyToStart: "Ready to start your project?",
    readyToStartDesc: "Contact us today to discuss your needs and get a personalized quote",

    // Services Page
    servicesPageSubtitle: "Complete expertise in pool, building, civil engineering and maintenance",
    completedProjects: "Completed projects",
    projectWarranty: "Project warranty",
    servicesGridSubtitle: "A complete range of services for all your construction projects",
    ourProjects: "Our Projects",
    ourProjectsDesc: "Discover some of our recently completed projects",
    ourProcess: "Our Process",
    ourProcessDesc: "A proven process to ensure the success of your project",
    servicesCtaDesc: "Contact us for a free consultation and a detailed quote",
    requestFreeQuote: "Request a free quote",
    servicePiscineTitle: "Pool Construction",
    servicePiscineDesc: "Custom design and construction of residential and commercial swimming pools.",
    servicePiscineFeature1: "In-ground and semi-in-ground pools",
    servicePiscineFeature2: "Modern filtration systems",
    servicePiscineFeature3: "Landscaping",
    servicePiscineFeature4: "Integrated LED lighting",
    serviceBatimentTitle: "Building Construction",
    serviceBatimentDesc: "Complete construction of residential, commercial and industrial buildings.",
    serviceBatimentFeature1: "Individual houses",
    serviceBatimentFeature2: "Commercial buildings",
    serviceBatimentFeature3: "Renovation and extension",
    serviceBatimentFeature4: "Industrial warehouses",
    serviceRouteTitle: "Civil Engineering & Roads",
    serviceRouteDesc: "Civil engineering and road construction for the public and private sectors.",
    serviceRouteFeature1: "Road construction",
    serviceRouteFeature2: "Earthworks",
    serviceRouteFeature3: "Drainage and sanitation",
    serviceRouteFeature4: "Special foundations",
    serviceEntretienTitle: "Maintenance & Servicing",
    serviceEntretienDesc: "Maintenance and servicing for all your infrastructures",
    serviceEntretienFeature1: "Pool maintenance",
    serviceEntretienFeature2: "Building repairs",
    serviceEntretienFeature3: "Road maintenance",
    serviceEntretienFeature4: "Maintenance contracts",
    galleryPiscineLuxe: "Luxury Residential Pool",
    galleryImmeubleCommercial: "Commercial Building",
    galleryRouteUrbaine: "Urban Road",
    galleryPiscineOlympique: "Olympic Swimming Pool",
    galleryVillaModerne: "Modern Villa",
    galleryInfraRoutiere: "Road Infrastructure",
    processConsultation: "Consultation",
    processConsultationDesc: "Analysis of your needs and feasibility study",
    processDevis: "Quote",
    processDevisDesc: "Detailed proposal with cost estimation",
    processRealisation: "Realization",
    processRealisationDesc: "Execution of the project by our expert teams",
    processLivraison: "Delivery",
    processLivraisonDesc: "Reception of the work and guaranteed warranty",

    // Alimentation Page
    foodPageSubtitle: "Discover our wide range of quality food products: rice, oils, canned goods and essential foodstuffs",
    searchProduct: "Search for a product...",
    noProductFound: "No product found",
    qualityGuaranteed: "Guaranteed Quality Products",
    qualityGuaranteedDesc: "All our food products are carefully selected for their quality and freshness. We work with trusted suppliers to guarantee you the best prices.",
    contactForBulk: "Contact us for your wholesale orders",
    "Riz Parfumé Thai": "Thai Fragrant Rice",
    "Riz Blanc Local": "Local White Rice",
    "Riz Basmati": "Basmati Rice",
    "Huile de Palme": "Palm Oil",
    "Huile d'Arachide": "Peanut Oil",
    "Huile Végétale": "Vegetable Oil",
    "Tomates Concentrées": "Concentrated Tomatoes",
    "Sardines à la Tomate": "Sardines in Tomato",
    "Maïs en Grains": "Corn Kernels",
    "Haricots Blancs": "White Beans",
    "Lentilles": "Lentils",
    "Pois Chiches": "Chickpeas",
    "Farine de Blé": "Wheat Flour",
    "Semoule de Maïs": "Corn Semolina",
    "Sel de Cuisine": "Kitchen Salt",

    // Produits Page
    productsPageSubtitle: "A complete range of cosmetic and hygiene products for the whole family",
    searchProductOrBrand: "Search for a product or brand...",
    currentPromotions: "Current Promotions",
    currentPromotionsDesc: "Take advantage of our special offers on a selection of products",
    ourPartnerBrands: "Our Partner Brands",
    bulkOrder: "Bulk Order",
    bulkOrderDesc: "Are you a reseller? Take advantage of our preferential rates for volume purchases",
    requestProQuote: "Request a professional quote",
    "Dentifrice Blancheur": "Whitening Toothpaste",
    "Dentifrice Protection Complète": "Complete Protection Toothpaste",
    "Dentifrice Herbes Naturelles": "Natural Herbs Toothpaste",
    "Savon Noir Africain": "African Black Soap",
    "Savon au Karité": "Shea Butter Soap",
    "Savon Antibactérien": "Antibacterial Soap",
    "Savon Doux pour Bébé": "Mild Baby Soap",
    "Shampoing Cheveux Secs": "Dry Hair Shampoo",
    "Shampoing Anti-Pelliculaire": "Anti-Dandruff Shampoo",
    "Shampoing Pour Enfants": "Kids Shampoo",
    "Crème Hydratante Visage": "Moisturizing Face Cream",
    "Crème Anti-Age": "Anti-Aging Cream",
    "Crème Éclaircissante": "Lightening Cream",
    "Parfum Homme Sport": "Sport Men's Perfume",
    "Parfum Femme Floral": "Floral Women's Perfume",
    "Lait Corporel Nourrissant": "Nourishing Body Lotion",
    "Fresh Smile": "Fresh Smile",
    "DentalCare": "DentalCare",
    "NaturaFresh": "NaturaFresh",
    "African Beauty": "African Beauty",
    "Shea Nature": "Shea Nature",
    "ProtectPlus": "ProtectPlus",
    "BabyCare": "BabyCare",
    "HydraHair": "HydraHair",
    "ScalpCare": "ScalpCare",
    "KidsClean": "KidsClean",
    "GlowSkin": "GlowSkin",
    "YouthRevive": "YouthRevive",
    "BrightGlow": "BrightGlow",
    "Elite Men": "Elite Men",
    "Elegance": "Elegance",
    "BodyCare": "BodyCare",

    // About Page
    aboutPageTitle: "About ETS ROYAL COMPANY SERVICE",
    ourStoryTitle: "Our Story",
    ourStoryDesc1: "Founded over 10 years ago, ETS ROYAL COMPANY SERVICE started as a small family business with a big vision: to provide quality essential products and services to our community.",
    ourStoryDesc2: "Over the years, we have expanded our activities to include three major poles: general food, cosmetic products and construction services. This diversification allows us to meet a wider range of needs while maintaining our commitment to excellence.",
    ourStoryDesc3: "Today, we are proud to be a major player in our fields of activity, recognized for our reliability, our integrity and the quality of our work.",
    ourCompanyAlt: "Our company",
    ourValuesTitle: "Our Values",
    ourValuesDesc: "The principles that guide each of our actions.",
    valueQualityTitle: "Quality",
    valueQualityDesc: "We are committed to providing products and services that meet the highest quality standards.",
    valueIntegrityTitle: "Integrity",
    valueIntegrityDesc: "We operate with transparency and honesty in all our interactions.",
    valueSatisfactionTitle: "Customer Satisfaction",
    valueSatisfactionDesc: "Customer satisfaction is at the heart of our priorities. We listen and respond to their needs.",
    valueInnovationTitle: "Innovation",
    valueInnovationDesc: "We are constantly seeking to innovate to improve our offers and our processes.",
    ourTeamTitle: "Our Team",
    ourTeamDesc: "Meet the leaders who drive our company to success.",
    teamRoleCEO: "Founder & CEO",
    teamRoleCOO: "Chief Operating Officer",
    teamRoleConstructionManager: "Construction Project Manager",
    teamRoleFoodManager: "Food Manager",
    workTogetherTitle: "Let's Work Together",
    workTogetherDesc: "Contact us today to discuss your needs and find out how we can help you.",

    // Contact Page
    contactPageSubtitle: "A question? A project? Our team is at your disposal to assist you",
    phone: "Phone",
    email: "Email",
    address: "Address",
    formTitle: "Send us a message",
    formDescription: "Fill out the form below and we will get back to you shortly",
    formFullName: "Full Name",
    formFullNamePlaceholder: "Your name",
    formEmail: "Email",
    formEmailPlaceholder: "your@email.com",
    formPhone: "Phone",
    formCategory: "Category",
    formSelectCategory: "Select a category",
    formSubject: "Subject",
    formSubjectPlaceholder: "Subject of your message",
    formMessage: "Message",
    formMessagePlaceholder: "Describe your request in detail...",
    formSubmitting: "Submitting...",
    formSubmit: "Send Message",
    toastSuccessTitle: "Message sent!",
    toastSuccessDescription: "We will get back to you as soon as possible.",
    openingHours: "Opening Hours",
    mondayFriday: "Monday - Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    closed: "Closed",
    needQuoteTitle: "Need a quote?",
    needQuoteDesc: "Get a free and detailed estimate for your project in less than 48 hours",
    needQuoteFeature1: "Free, no-obligation quote",
    needQuoteFeature2: "Quick response within 48 hours",
    needQuoteFeature3: "Personalized advice",
    faqTitle: "Quick FAQ",
    faq1Title: "Delivery available?",
    faq1Desc: "Yes, for all wholesale orders",
    faq2Title: "Payment accepted?",
    faq2Desc: "Cash, Mobile Money, Bank Transfer",
    faq3Title: "Work warranty?",
    faq3Desc: "5-year warranty on all our projects",
    ourOffices: "Our Offices",
    mapPlaceholder: "Interactive map coming soon",

    // Footer
    quickLinks: "Quick Links",
    country: "Cameroon",
    allRightsReserved: "All rights reserved.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language | null
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const toggleLanguage = () => {
    const newLanguage = language === "fr" ? "en" : "fr"
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string): string => {
    const translation = translations[language][key as keyof (typeof translations)["fr"]];
    if (translation) {
      return translation;
    }
    // Fallback to French if the key is not found in the current language
    return translations["fr"][key as keyof (typeof translations)["fr"]] || key
  }

  return <LanguageContext.Provider value={{ language, toggleLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within LanguageProvider")
  return context
}